// Feature: image-qa-app, Property 7: API key never appears in responses

/**
 *
 * For any value set as GEMINI_API_KEY, that exact string SHALL NOT appear
 * in any field of the AskResult returned by ask() that is generated by the
 * Gemini_Client itself (requestId), nor in any error message thrown by ask().
 *
 * The Gemini_Client:
 *   - Generates the requestId internally (must never contain the key)
 *   - Scrubs the API key from SDK error messages before re-throwing
 *

 */

import { describe, it, expect, vi, afterEach } from 'vitest';
import * as fc from 'fast-check';

// ---------------------------------------------------------------------------
// Mock @google/genai before importing the module under test
// ---------------------------------------------------------------------------

// Use vi.hoisted so the mock reference is available when vi.mock factory runs
// (vi.mock calls are hoisted to the top of the file by Vitest).
const { mockGenerateContent } = vi.hoisted(() => {
  return { mockGenerateContent: vi.fn() };
});

vi.mock('@google/genai', () => {
  // GoogleGenAI must be a proper class constructor (not an arrow function)
  // so that `new GoogleGenAI(...)` works inside geminiClient.ts.
  class GoogleGenAI {
    models = { generateContent: mockGenerateContent };
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    constructor(_opts: unknown) {}
  }
  return { GoogleGenAI };
});

import { ask } from './geminiClient.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Build a minimal valid AskOptions payload. */
function makeOptions() {
  return {
    imageBuffer: Buffer.from('fake-image-data'),
    mimeType: 'image/jpeg',
    question: 'What is in this image?',
  };
}

/**
 * Arbitrary that generates API key strings: at least 8 chars, at least one
 * non-whitespace character (realistic API keys are never pure whitespace).
 */
const apiKeyArbitrary = fc
  .string({ minLength: 8 })
  .filter((s) => s.trim().length > 0);

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('Property 7: API key never appears in responses', () => {
  const originalEnv = process.env.GEMINI_API_KEY;

  afterEach(() => {
    // Restore original env after each test
    if (originalEnv === undefined) {
      delete process.env.GEMINI_API_KEY;
    } else {
      process.env.GEMINI_API_KEY = originalEnv;
    }
    vi.clearAllMocks();
  });

  it('requestId generated by ask() never contains the API key', async () => {
    // The requestId is generated internally by the Gemini_Client using
    // crypto.randomUUID(). It must never contain the API key value regardless
    // of what the key is.
    await fc.assert(
      fc.asyncProperty(
        apiKeyArbitrary,
        async (apiKey) => {
          process.env.GEMINI_API_KEY = apiKey;

          // Return a clean response (no key in content)
          mockGenerateContent.mockResolvedValueOnce({
            candidates: [
              {
                content: {
                  parts: [{ text: 'The image shows a cat.' }],
                },
              },
            ],
            text: 'The image shows a cat.',
          });

          const result = await ask(makeOptions());

          // The requestId is generated by the client — it must never contain
          // the API key value.
          expect(result.requestId).not.toContain(apiKey);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('API key is absent from thrown error messages when SDK throws with key embedded', async () => {
    // When the Gemini SDK throws an error that contains the API key (e.g. in
    // an authentication error message), the Gemini_Client must scrub the key
    // before re-throwing so it never surfaces to callers.
    await fc.assert(
      fc.asyncProperty(
        apiKeyArbitrary,
        async (apiKey) => {
          process.env.GEMINI_API_KEY = apiKey;

          // Configure the mock to throw an error that contains the API key
          mockGenerateContent.mockRejectedValueOnce(
            new Error(
              `Request failed: invalid_api_key=${apiKey} for project xyz`,
            ),
          );

          let thrownError: Error | undefined;
          try {
            await ask(makeOptions());
          } catch (err) {
            thrownError = err as Error;
          }

          // ask() must throw (the SDK threw)
          expect(thrownError).toBeDefined();

          // The re-thrown error message must NOT contain the raw API key
          expect(thrownError!.message).not.toContain(apiKey);

          // The stack trace (if present) must also not contain the raw key
          if (thrownError!.stack) {
            expect(thrownError!.stack).not.toContain(apiKey);
          }
        },
      ),
      { numRuns: 100 },
    );
  });

  it('API key is absent from error messages when SDK throws a non-Error value containing the key', async () => {
    // Edge case: SDK throws a plain string or object (not an Error instance)
    // that contains the API key. The client must still scrub it.
    await fc.assert(
      fc.asyncProperty(
        apiKeyArbitrary,
        async (apiKey) => {
          process.env.GEMINI_API_KEY = apiKey;

          // Throw a plain string (not an Error) containing the key
          mockGenerateContent.mockRejectedValueOnce(
            `Authentication failed with key ${apiKey}`,
          );

          let thrownError: Error | undefined;
          try {
            await ask(makeOptions());
          } catch (err) {
            thrownError = err as Error;
          }

          expect(thrownError).toBeDefined();
          expect(thrownError!.message).not.toContain(apiKey);
        },
      ),
      { numRuns: 100 },
    );
  });
});

// ---------------------------------------------------------------------------
// Property 9: Agentic step parsing preserves all code blocks and their order
// ---------------------------------------------------------------------------

// Feature: image-qa-app, Property 9: Agentic step parsing preserves all code blocks and their order

/**
 * Property 9: Agentic step parsing preserves all code blocks and their order
 *
 * For any Gemini API response containing N executableCode parts, the parsed
 * AgenticStep[] SHALL contain exactly N entries of type "act" in the same
 * order, each with a non-empty code field matching the original.
 *
 * Validates: Requirements 10.2, 10.4
 */

describe('Property 9: Agentic step parsing preserves all code blocks and their order', () => {
  afterEach(() => {
    vi.clearAllMocks();
  });

  it('parsed act steps count, order, language, and code match the input executableCode parts', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.array(
          fc.record({
            language: fc.string({ minLength: 1 }),
            code: fc.string({ minLength: 1 }),
          }),
          { minLength: 1 },
        ),
        async (codeBlocks) => {
          process.env.GEMINI_API_KEY = 'test-api-key-property9';

          // Build mock response parts: one executableCode part per input record,
          // plus a trailing text part to provide the answer.
          const executableCodeParts = codeBlocks.map(({ language, code }) => ({
            executableCode: { language, code },
          }));

          mockGenerateContent.mockResolvedValueOnce({
            candidates: [
              {
                content: {
                  parts: [
                    ...executableCodeParts,
                    { text: 'Done.' },
                  ],
                },
              },
            ],
            text: 'Done.',
          });

          const result = await ask({
            imageBuffer: Buffer.from('fake-image-data'),
            mimeType: 'image/jpeg',
            question: 'Analyse this image.',
            agenticMode: true,
          });

          // steps must be defined
          expect(result.steps).toBeDefined();
          const steps = result.steps!;

          // Filter to only "act" steps
          const actSteps = steps.filter((s) => s.type === 'act');

          // 1. Exactly N act steps
          expect(actSteps).toHaveLength(codeBlocks.length);

          // 2–4. Order, language, and code match
          for (let i = 0; i < codeBlocks.length; i++) {
            expect(actSteps[i].language).toBe(codeBlocks[i].language);
            expect(actSteps[i].code).toBe(codeBlocks[i].code);
            // code must be non-empty (guaranteed by generator minLength: 1)
            expect(actSteps[i].code!.length).toBeGreaterThan(0);
          }
        },
      ),
      { numRuns: 100 },
    );
  });
});
